### ISSUE TITLE
SqlClient运行报错

### ISSUE THREAD

**Issue by jiajingsi** [intsmaze/flink-boot#3]
通过继承BaseFlink实现的com.intsmaze.flink.client.SqlClient，运行的时候报错，查了一些资料说是需要给实体类添加无参构造，但是实际是存在的 com.intsmaze.flink.base.bean.SourceData，但仍然报如下的错误。
报错信息：
Exception in thread "main" org.apache.flink.table.api.ValidationException: Too many fields referenced from an atomic type.
	at org.apache.flink.table.typeutils.FieldInfoUtils.extractFieldInfoFromAtomicType(FieldInfoUtils.java:393)
	at org.apache.flink.table.typeutils.FieldInfoUtils.extractFieldInformation(FieldInfoUtils.java:264)
	at org.apache.flink.table.typeutils.FieldInfoUtils.getFieldsInfo(FieldInfoUtils.java:232)
	at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.lambda$asQueryOperation$0(StreamTableEnvironmentImpl.java:415)
	at java.util.Optional.map(Optional.java:215)
	at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.asQueryOperation(StreamTableEnvironmentImpl.java:414)
	at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.fromDataStream(StreamTableEnvironmentImpl.java:205)
	at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.createTemporaryView(StreamTableEnvironmentImpl.java:229)
	at org.apache.flink.table.api.java.internal.StreamTableEnvironmentImpl.registerDataStream(StreamTableEnvironmentImpl.java:224)

**Comment by intsmaze** [comment]
etl.sql文件与SQLClient类指定路径保持一致，重新拉flink-sql moel工程，里面移动了对应文件的路径
